// This code belongs to the package net.stormofsorts.agotmod.item
package net.darkflameproduction.agotmod.item.creativetabs;

// Importing necessary classes from other packages

import net.darkflameproduction.agotmod.AGoTMod;
import net.darkflameproduction.agotmod.block.ModBLocks;
import net.darkflameproduction.agotmod.item.ModItems;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.ItemStack;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

// A utility class for creating custom creative mode tabs
public class ModCreativeToolsUtilities {

    // Deferred register for creative mode tabs
    public static final DeferredRegister<CreativeModeTab> CREATIVE_MODE_TAB =
            DeferredRegister.create(Registries.CREATIVE_MODE_TAB, AGoTMod.MOD_ID);

    // Adding items into the MAIN mod tab in creative
    public static final DeferredHolder<CreativeModeTab, CreativeModeTab> AGOT_TAB_TOOLS = CREATIVE_MODE_TAB.register("agot_tab_tools_utilities",
            () -> CreativeModeTab.builder()
                    .icon(() -> new ItemStack(ModItems.STEEL_PICKAXE.get())) // Icon for the creative mode tab
                    .title(Component.translatable("creativetab.agot_tab_tools_utilities")) // Title for the creative mode tab
                    .displayItems((pParameters, pOutput) -> {
                        /** TOOLS */
                        pOutput.accept(ModItems.BRONZE_AXE.get());
                        pOutput.accept(ModItems.BRONZE_HOE.get());
                        pOutput.accept(ModItems.BRONZE_PICKAXE.get());
                        pOutput.accept(ModItems.BRONZE_SHOVEL.get());

                        pOutput.accept(ModItems.STEEL_AXE.get());
                        pOutput.accept(ModItems.STEEL_HOE.get());
                        pOutput.accept(ModItems.STEEL_PICKAXE.get());
                        pOutput.accept(ModItems.STEEL_SHOVEL.get());
// Town Hall (existing)
                        pOutput.accept(ModItems.TOWN_HALL.get());

// All Job Barrel Creative Tab Entries
                        pOutput.accept(ModItems.ALEHOUSE_BARREL.get());
                        pOutput.accept(ModItems.ARMORSMITH_BARREL.get());
                        pOutput.accept(ModItems.BAKER_BARREL.get());
                        pOutput.accept(ModItems.BANKER_BARREL.get());
                        pOutput.accept(ModItems.BARD_BARREL.get());
                        pOutput.accept(ModItems.BLACKSMITH_BARREL.get());
                        pOutput.accept(ModItems.BUILDER_BARREL.get());
                        pOutput.accept(ModItems.BUTCHER_BARREL.get());
                        pOutput.accept(ModItems.CARAVAN_MASTER_BARREL.get());
                        pOutput.accept(ModItems.CARPENTER_BARREL.get());
                        pOutput.accept(ModItems.CATTLE_HERDER_BARREL.get());
                        pOutput.accept(ModItems.CHARCOAL_BURNER_BARREL.get());
                        pOutput.accept(ModItems.CHICKEN_BREEDER_BARREL.get());
                        pOutput.accept(ModItems.FARMER_BARREL.get());
                        pOutput.accept(ModItems.GOAT_HERDER_BARREL.get());
                        pOutput.accept(ModItems.GROCER_BARREL.get());
                        pOutput.accept(ModItems.GUARD_BARREL.get());
                        pOutput.accept(ModItems.HERBALIST_BARREL.get());
                        pOutput.accept(ModItems.HORSE_BREEDER_BARREL.get());
                        pOutput.accept(ModItems.HUNTER_BARREL.get());
                        pOutput.accept(ModItems.INNKEEPER_BARREL.get());
                        pOutput.accept(ModItems.JEWELER_BARREL.get());
                        pOutput.accept(ModItems.LUMBERJACK_BARREL.get());
                        pOutput.accept(ModItems.MAESTER_BARREL.get());
                        pOutput.accept(ModItems.MINER_BARREL.get());
                        pOutput.accept(ModItems.PIG_BREEDER_BARREL.get());
                        pOutput.accept(ModItems.PYROMANCER_BARREL.get());
                        pOutput.accept(ModItems.QUARRY_BARREL.get());
                        pOutput.accept(ModItems.SCRIBE_BARREL.get());
                        pOutput.accept(ModItems.SEPTON_BARREL.get());
                        pOutput.accept(ModItems.SHEEP_HERDER_BARREL.get());
                        pOutput.accept(ModItems.SHIPWRIGHT_BARREL.get());
                        pOutput.accept(ModItems.SLAVER_BARREL.get());
                        pOutput.accept(ModItems.SMELTER_BARREL.get());
                        pOutput.accept(ModItems.STONEMASON_BARREL.get());
                        pOutput.accept(ModItems.SWORDSMITH_BARREL.get());
                        pOutput.accept(ModItems.TAILOR_BARREL.get());
                        pOutput.accept(ModItems.TANNER_BARREL.get());
                        pOutput.accept(ModItems.TRADER_BARREL.get());
                        pOutput.accept(ModItems.OAK_TABLE.get());
                        pOutput.accept(ModItems.DARK_OAK_TABLE.get());
                        pOutput.accept(ModItems.SPRUCE_TABLE.get());
                        pOutput.accept(ModItems.BIRCH_TABLE.get());
                        pOutput.accept(ModItems.JUNGLE_TABLE.get());
                        pOutput.accept(ModItems.ACACIA_TABLE.get());
                        pOutput.accept(ModItems.MANGROVE_TABLE.get());
                        pOutput.accept(ModItems.CHERRY_TABLE.get());
                        pOutput.accept(ModItems.BAMBOO_TABLE.get());
                        pOutput.accept(ModItems.CRIMSON_TABLE.get());
                        pOutput.accept(ModItems.WARPED_TABLE.get());
                        pOutput.accept(ModItems.WEIRWOOD_TABLE.get());
                        pOutput.accept(ModItems.CHARRED_TABLE.get());
                        pOutput.accept(ModItems.ROTTEN_TABLE.get());
                        pOutput.accept(ModItems.PINE_TABLE.get());
                        pOutput.accept(ModItems.SOLDIER_PINE_TABLE.get());
                        pOutput.accept(ModItems.BLUE_SOLDIER_PINE_TABLE.get());
                        pOutput.accept(ModItems.ASH_TABLE.get());
                        pOutput.accept(ModItems.BEECH_TABLE.get());
                        pOutput.accept(ModItems.CEDAR_TABLE.get());
                        pOutput.accept(ModItems.CHESTNUT_TABLE.get());
                        pOutput.accept(ModItems.HAWTHORN_TABLE.get());
                        pOutput.accept(ModItems.IRONWOOD_TABLE.get());
                        pOutput.accept(ModItems.SENTINEL_TABLE.get());
                        pOutput.accept(ModItems.SYCAMORE_TABLE.get());
                        pOutput.accept(ModItems.BLACKBARK_TABLE.get());
                        pOutput.accept(ModItems.ASPEN_TABLE.get());
                        pOutput.accept(ModItems.ALDER_TABLE.get());
                        pOutput.accept(ModItems.BLACK_CHERRY_TABLE.get());
                        pOutput.accept(ModItems.BLACK_OLIVE_TABLE.get());
                        pOutput.accept(ModItems.CRABAPPLE_TABLE.get());
                        pOutput.accept(ModItems.OLIVE_TABLE.get());
                        pOutput.accept(ModItems.WHITE_CHERRY_TABLE.get());
                        pOutput.accept(ModItems.RED_CHERRY_TABLE.get());
                        pOutput.accept(ModItems.FIR_TABLE.get());
                        pOutput.accept(ModItems.WILLOW_TABLE.get());
                        pOutput.accept(ModItems.WORMTREE_TABLE.get());
                        pOutput.accept(ModItems.ALMOND_TABLE.get());
                        pOutput.accept(ModItems.APPLE_TABLE.get());
                        pOutput.accept(ModItems.APRICOT_TABLE.get());
                        pOutput.accept(ModItems.BAOBAB_TABLE.get());
                        pOutput.accept(ModItems.BLACK_COTTONWOOD_TABLE.get());
                        pOutput.accept(ModItems.BLACKTHORN_TABLE.get());
                        pOutput.accept(ModItems.BLOOD_ORANGE_TABLE.get());
                        pOutput.accept(ModItems.BLOODWOOD_TABLE.get());
                        pOutput.accept(ModItems.BLUE_MAHOE_TABLE.get());
                        pOutput.accept(ModItems.COTTONWOOD_TABLE.get());
                        pOutput.accept(ModItems.DATEPALM_TABLE.get());
                        pOutput.accept(ModItems.EBONY_TABLE.get());
                        pOutput.accept(ModItems.FIG_TABLE.get());
                        pOutput.accept(ModItems.FIREPLUM_TABLE.get());
                        pOutput.accept(ModItems.GOLDENHEART_TABLE.get());
                        pOutput.accept(ModItems.LEMON_TABLE.get());
                        pOutput.accept(ModItems.LIME_TABLE.get());
                        pOutput.accept(ModItems.LINDEN_TABLE.get());
                        pOutput.accept(ModItems.MAHOGANY_TABLE.get());
                        pOutput.accept(ModItems.MAPLE_TABLE.get());
                        pOutput.accept(ModItems.MYRRH_TABLE.get());
                        pOutput.accept(ModItems.NIGHTWOOD_TABLE.get());
                        pOutput.accept(ModItems.NUTMEG_TABLE.get());
                        pOutput.accept(ModItems.ORANGE_TABLE.get());
                        pOutput.accept(ModItems.PEACH_TABLE.get());
                        pOutput.accept(ModItems.PEAR_TABLE.get());
                        pOutput.accept(ModItems.PECAN_TABLE.get());
                        pOutput.accept(ModItems.PERSIMMON_TABLE.get());
                        pOutput.accept(ModItems.PINK_IVORY_TABLE.get());
                        pOutput.accept(ModItems.PLUM_TABLE.get());
                        pOutput.accept(ModItems.POMEGRANATE_TABLE.get());
                        pOutput.accept(ModItems.PURPLEHEART_TABLE.get());
                        pOutput.accept(ModItems.REDWOOD_TABLE.get());
                        pOutput.accept(ModItems.SANDALWOOD_TABLE.get());
                        pOutput.accept(ModItems.SANDBEGGAR_TABLE.get());
                        pOutput.accept(ModItems.TIGERWOOD_TABLE.get());
                        pOutput.accept(ModItems.YEW_TABLE.get());

// ── CHAIRS ────────────────────────────────────────────────────────────────
                        pOutput.accept(ModItems.DARK_OAK_CHAIR.get());
                        pOutput.accept(ModItems.OAK_CHAIR.get());
                        pOutput.accept(ModItems.SPRUCE_CHAIR.get());
                        pOutput.accept(ModItems.BIRCH_CHAIR.get());
                        pOutput.accept(ModItems.JUNGLE_CHAIR.get());
                        pOutput.accept(ModItems.ACACIA_CHAIR.get());
                        pOutput.accept(ModItems.MANGROVE_CHAIR.get());
                        pOutput.accept(ModItems.CHERRY_CHAIR.get());
                        pOutput.accept(ModItems.BAMBOO_CHAIR.get());
                        pOutput.accept(ModItems.CRIMSON_CHAIR.get());
                        pOutput.accept(ModItems.WARPED_CHAIR.get());
                        pOutput.accept(ModItems.WEIRWOOD_CHAIR.get());
                        pOutput.accept(ModItems.CHARRED_CHAIR.get());
                        pOutput.accept(ModItems.ROTTEN_CHAIR.get());
                        pOutput.accept(ModItems.PINE_CHAIR.get());
                        pOutput.accept(ModItems.SOLDIER_PINE_CHAIR.get());
                        pOutput.accept(ModItems.BLUE_SOLDIER_PINE_CHAIR.get());
                        pOutput.accept(ModItems.ASH_CHAIR.get());
                        pOutput.accept(ModItems.BEECH_CHAIR.get());
                        pOutput.accept(ModItems.CEDAR_CHAIR.get());
                        pOutput.accept(ModItems.CHESTNUT_CHAIR.get());
                        pOutput.accept(ModItems.HAWTHORN_CHAIR.get());
                        pOutput.accept(ModItems.IRONWOOD_CHAIR.get());
                        pOutput.accept(ModItems.SENTINEL_CHAIR.get());
                        pOutput.accept(ModItems.SYCAMORE_CHAIR.get());
                        pOutput.accept(ModItems.BLACKBARK_CHAIR.get());
                        pOutput.accept(ModItems.ASPEN_CHAIR.get());
                        pOutput.accept(ModItems.ALDER_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_CHERRY_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_OLIVE_CHAIR.get());
                        pOutput.accept(ModItems.CRABAPPLE_CHAIR.get());
                        pOutput.accept(ModItems.OLIVE_CHAIR.get());
                        pOutput.accept(ModItems.WHITE_CHERRY_CHAIR.get());
                        pOutput.accept(ModItems.RED_CHERRY_CHAIR.get());
                        pOutput.accept(ModItems.FIR_CHAIR.get());
                        pOutput.accept(ModItems.WILLOW_CHAIR.get());
                        pOutput.accept(ModItems.WORMTREE_CHAIR.get());
                        pOutput.accept(ModItems.ALMOND_CHAIR.get());
                        pOutput.accept(ModItems.APPLE_CHAIR.get());
                        pOutput.accept(ModItems.APRICOT_CHAIR.get());
                        pOutput.accept(ModItems.BAOBAB_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_COTTONWOOD_CHAIR.get());
                        pOutput.accept(ModItems.BLACKTHORN_CHAIR.get());
                        pOutput.accept(ModItems.BLOOD_ORANGE_CHAIR.get());
                        pOutput.accept(ModItems.BLOODWOOD_CHAIR.get());
                        pOutput.accept(ModItems.BLUE_MAHOE_CHAIR.get());
                        pOutput.accept(ModItems.COTTONWOOD_CHAIR.get());
                        pOutput.accept(ModItems.DATEPALM_CHAIR.get());
                        pOutput.accept(ModItems.EBONY_CHAIR.get());
                        pOutput.accept(ModItems.FIG_CHAIR.get());
                        pOutput.accept(ModItems.FIREPLUM_CHAIR.get());
                        pOutput.accept(ModItems.GOLDENHEART_CHAIR.get());
                        pOutput.accept(ModItems.LEMON_CHAIR.get());
                        pOutput.accept(ModItems.LIME_CHAIR.get());
                        pOutput.accept(ModItems.LINDEN_CHAIR.get());
                        pOutput.accept(ModItems.MAHOGANY_CHAIR.get());
                        pOutput.accept(ModItems.MAPLE_CHAIR.get());
                        pOutput.accept(ModItems.MYRRH_CHAIR.get());
                        pOutput.accept(ModItems.NIGHTWOOD_CHAIR.get());
                        pOutput.accept(ModItems.NUTMEG_CHAIR.get());
                        pOutput.accept(ModItems.ORANGE_CHAIR.get());
                        pOutput.accept(ModItems.PEACH_CHAIR.get());
                        pOutput.accept(ModItems.PEAR_CHAIR.get());
                        pOutput.accept(ModItems.PECAN_CHAIR.get());
                        pOutput.accept(ModItems.PERSIMMON_CHAIR.get());
                        pOutput.accept(ModItems.PINK_IVORY_CHAIR.get());
                        pOutput.accept(ModItems.PLUM_CHAIR.get());
                        pOutput.accept(ModItems.POMEGRANATE_CHAIR.get());
                        pOutput.accept(ModItems.PURPLEHEART_CHAIR.get());
                        pOutput.accept(ModItems.REDWOOD_CHAIR.get());
                        pOutput.accept(ModItems.SANDALWOOD_CHAIR.get());
                        pOutput.accept(ModItems.SANDBEGGAR_CHAIR.get());
                        pOutput.accept(ModItems.TIGERWOOD_CHAIR.get());
                        pOutput.accept(ModItems.YEW_CHAIR.get());

// ── ARM CHAIRS ────────────────────────────────────────────────────────────
                        pOutput.accept(ModItems.DARK_OAK_ARM_CHAIR.get());
                        pOutput.accept(ModItems.OAK_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SPRUCE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BIRCH_ARM_CHAIR.get());
                        pOutput.accept(ModItems.JUNGLE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ACACIA_ARM_CHAIR.get());
                        pOutput.accept(ModItems.MANGROVE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CHERRY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BAMBOO_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CRIMSON_ARM_CHAIR.get());
                        pOutput.accept(ModItems.WARPED_ARM_CHAIR.get());
                        pOutput.accept(ModItems.WEIRWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CHARRED_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ROTTEN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PINE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SOLDIER_PINE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLUE_SOLDIER_PINE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ASH_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BEECH_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CEDAR_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CHESTNUT_ARM_CHAIR.get());
                        pOutput.accept(ModItems.HAWTHORN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.IRONWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SENTINEL_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SYCAMORE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLACKBARK_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ASPEN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ALDER_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_CHERRY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_OLIVE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.CRABAPPLE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.OLIVE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.WHITE_CHERRY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.RED_CHERRY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.FIR_ARM_CHAIR.get());
                        pOutput.accept(ModItems.WILLOW_ARM_CHAIR.get());
                        pOutput.accept(ModItems.WORMTREE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ALMOND_ARM_CHAIR.get());
                        pOutput.accept(ModItems.APPLE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.APRICOT_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BAOBAB_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLACK_COTTONWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLACKTHORN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLOOD_ORANGE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLOODWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.BLUE_MAHOE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.COTTONWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.DATEPALM_ARM_CHAIR.get());
                        pOutput.accept(ModItems.EBONY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.FIG_ARM_CHAIR.get());
                        pOutput.accept(ModItems.FIREPLUM_ARM_CHAIR.get());
                        pOutput.accept(ModItems.GOLDENHEART_ARM_CHAIR.get());
                        pOutput.accept(ModItems.LEMON_ARM_CHAIR.get());
                        pOutput.accept(ModItems.LIME_ARM_CHAIR.get());
                        pOutput.accept(ModItems.LINDEN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.MAHOGANY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.MAPLE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.MYRRH_ARM_CHAIR.get());
                        pOutput.accept(ModItems.NIGHTWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.NUTMEG_ARM_CHAIR.get());
                        pOutput.accept(ModItems.ORANGE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PEACH_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PEAR_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PECAN_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PERSIMMON_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PINK_IVORY_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PLUM_ARM_CHAIR.get());
                        pOutput.accept(ModItems.POMEGRANATE_ARM_CHAIR.get());
                        pOutput.accept(ModItems.PURPLEHEART_ARM_CHAIR.get());
                        pOutput.accept(ModItems.REDWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SANDALWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.SANDBEGGAR_ARM_CHAIR.get());
                        pOutput.accept(ModItems.TIGERWOOD_ARM_CHAIR.get());
                        pOutput.accept(ModItems.YEW_ARM_CHAIR.get());

// ── STOOLS ────────────────────────────────────────────────────────────────
                        pOutput.accept(ModItems.DARK_OAK_STOOL.get());
                        pOutput.accept(ModItems.OAK_STOOL.get());
                        pOutput.accept(ModItems.SPRUCE_STOOL.get());
                        pOutput.accept(ModItems.BIRCH_STOOL.get());
                        pOutput.accept(ModItems.JUNGLE_STOOL.get());
                        pOutput.accept(ModItems.ACACIA_STOOL.get());
                        pOutput.accept(ModItems.MANGROVE_STOOL.get());
                        pOutput.accept(ModItems.CHERRY_STOOL.get());
                        pOutput.accept(ModItems.BAMBOO_STOOL.get());
                        pOutput.accept(ModItems.CRIMSON_STOOL.get());
                        pOutput.accept(ModItems.WARPED_STOOL.get());
                        pOutput.accept(ModItems.WEIRWOOD_STOOL.get());
                        pOutput.accept(ModItems.CHARRED_STOOL.get());
                        pOutput.accept(ModItems.ROTTEN_STOOL.get());
                        pOutput.accept(ModItems.PINE_STOOL.get());
                        pOutput.accept(ModItems.SOLDIER_PINE_STOOL.get());
                        pOutput.accept(ModItems.BLUE_SOLDIER_PINE_STOOL.get());
                        pOutput.accept(ModItems.ASH_STOOL.get());
                        pOutput.accept(ModItems.BEECH_STOOL.get());
                        pOutput.accept(ModItems.CEDAR_STOOL.get());
                        pOutput.accept(ModItems.CHESTNUT_STOOL.get());
                        pOutput.accept(ModItems.HAWTHORN_STOOL.get());
                        pOutput.accept(ModItems.IRONWOOD_STOOL.get());
                        pOutput.accept(ModItems.SENTINEL_STOOL.get());
                        pOutput.accept(ModItems.SYCAMORE_STOOL.get());
                        pOutput.accept(ModItems.BLACKBARK_STOOL.get());
                        pOutput.accept(ModItems.ASPEN_STOOL.get());
                        pOutput.accept(ModItems.ALDER_STOOL.get());
                        pOutput.accept(ModItems.BLACK_CHERRY_STOOL.get());
                        pOutput.accept(ModItems.BLACK_OLIVE_STOOL.get());
                        pOutput.accept(ModItems.CRABAPPLE_STOOL.get());
                        pOutput.accept(ModItems.OLIVE_STOOL.get());
                        pOutput.accept(ModItems.WHITE_CHERRY_STOOL.get());
                        pOutput.accept(ModItems.RED_CHERRY_STOOL.get());
                        pOutput.accept(ModItems.FIR_STOOL.get());
                        pOutput.accept(ModItems.WILLOW_STOOL.get());
                        pOutput.accept(ModItems.WORMTREE_STOOL.get());
                        pOutput.accept(ModItems.ALMOND_STOOL.get());
                        pOutput.accept(ModItems.APPLE_STOOL.get());
                        pOutput.accept(ModItems.APRICOT_STOOL.get());
                        pOutput.accept(ModItems.BAOBAB_STOOL.get());
                        pOutput.accept(ModItems.BLACK_COTTONWOOD_STOOL.get());
                        pOutput.accept(ModItems.BLACKTHORN_STOOL.get());
                        pOutput.accept(ModItems.BLOOD_ORANGE_STOOL.get());
                        pOutput.accept(ModItems.BLOODWOOD_STOOL.get());
                        pOutput.accept(ModItems.BLUE_MAHOE_STOOL.get());
                        pOutput.accept(ModItems.COTTONWOOD_STOOL.get());
                        pOutput.accept(ModItems.DATEPALM_STOOL.get());
                        pOutput.accept(ModItems.EBONY_STOOL.get());
                        pOutput.accept(ModItems.FIG_STOOL.get());
                        pOutput.accept(ModItems.FIREPLUM_STOOL.get());
                        pOutput.accept(ModItems.GOLDENHEART_STOOL.get());
                        pOutput.accept(ModItems.LEMON_STOOL.get());
                        pOutput.accept(ModItems.LIME_STOOL.get());
                        pOutput.accept(ModItems.LINDEN_STOOL.get());
                        pOutput.accept(ModItems.MAHOGANY_STOOL.get());
                        pOutput.accept(ModItems.MAPLE_STOOL.get());
                        pOutput.accept(ModItems.MYRRH_STOOL.get());
                        pOutput.accept(ModItems.NIGHTWOOD_STOOL.get());
                        pOutput.accept(ModItems.NUTMEG_STOOL.get());
                        pOutput.accept(ModItems.ORANGE_STOOL.get());
                        pOutput.accept(ModItems.PEACH_STOOL.get());
                        pOutput.accept(ModItems.PEAR_STOOL.get());
                        pOutput.accept(ModItems.PECAN_STOOL.get());
                        pOutput.accept(ModItems.PERSIMMON_STOOL.get());
                        pOutput.accept(ModItems.PINK_IVORY_STOOL.get());
                        pOutput.accept(ModItems.PLUM_STOOL.get());
                        pOutput.accept(ModItems.POMEGRANATE_STOOL.get());
                        pOutput.accept(ModItems.PURPLEHEART_STOOL.get());
                        pOutput.accept(ModItems.REDWOOD_STOOL.get());
                        pOutput.accept(ModItems.SANDALWOOD_STOOL.get());
                        pOutput.accept(ModItems.SANDBEGGAR_STOOL.get());
                        pOutput.accept(ModItems.TIGERWOOD_STOOL.get());
                        pOutput.accept(ModItems.YEW_STOOL.get());

                    })
                    .build());

    // Tells the AGoTMod class to call the modded tabs into the game
    public static void register(IEventBus eventBus) {
        CREATIVE_MODE_TAB.register(eventBus);
    }
}
