package net.darkflameproduction.agotmod.worldgen.tree;

import net.darkflameproduction.agotmod.worldgen.ModConfiguredFeatures;
import net.minecraft.world.level.block.grower.TreeGrower;

import java.util.Optional;

public class ModTreeGrower {
    public static final TreeGrower SYSCAMORE = new TreeGrower("syscamore", Optional.empty(), Optional.of(ModConfiguredFeatures.SYCAMORE_KEY), Optional.empty());
    public static final TreeGrower WEIRWOOD = new TreeGrower("weirwood", Optional.empty(), Optional.of(ModConfiguredFeatures.WEIRWOOD_KEY), Optional.empty());
    public static final TreeGrower SENTINEL = new TreeGrower("sentinel", Optional.empty(), Optional.of(ModConfiguredFeatures.SENTINEL_KEY), Optional.empty());
    public static final TreeGrower PINE = new TreeGrower("pine", Optional.empty(), Optional.of(ModConfiguredFeatures.PINE_KEY), Optional.empty());
    public static final TreeGrower IRONWOOD = new TreeGrower("ironwood", Optional.empty(), Optional.of(ModConfiguredFeatures.IRONWOOD_KEY), Optional.empty());
    public static final TreeGrower HAWTHORN = new TreeGrower("hawthorn", Optional.empty(), Optional.of(ModConfiguredFeatures.HAWTHORN_KEY), Optional.empty());
    public static final TreeGrower CHESTNUT = new TreeGrower("chestnut", Optional.empty(), Optional.of(ModConfiguredFeatures.CHESTNUT_KEY), Optional.empty());
    public static final TreeGrower CEDAR = new TreeGrower("cedar", Optional.empty(), Optional.of(ModConfiguredFeatures.CEDAR_KEY), Optional.empty());
    public static final TreeGrower BEECH = new TreeGrower("beech", Optional.empty(), Optional.of(ModConfiguredFeatures.BEECH_KEY), Optional.empty());
    public static final TreeGrower ASH = new TreeGrower("ash", Optional.empty(), Optional.of(ModConfiguredFeatures.ASH_KEY), Optional.empty());
    public static final TreeGrower BLACKBARK = new TreeGrower("blackbark", Optional.empty(), Optional.of(ModConfiguredFeatures.BLACKBARK_KEY), Optional.empty());
    public static final TreeGrower ASPEN = new TreeGrower("aspen", Optional.empty(), Optional.of(ModConfiguredFeatures.ASPEN_KEY), Optional.empty());
    public static final TreeGrower ALDER = new TreeGrower("alder", Optional.empty(), Optional.of(ModConfiguredFeatures.ALDER_KEY), Optional.empty());
    public static final TreeGrower BLACK_CHERRY = new TreeGrower("black_cherry", Optional.empty(), Optional.of(ModConfiguredFeatures.BLACK_CHERRY_KEY), Optional.empty());
    public static final TreeGrower BLACK_OLIVE = new TreeGrower("black_olive", Optional.empty(), Optional.of(ModConfiguredFeatures.BLACK_OLIVE_KEY), Optional.empty());
    public static final TreeGrower CRABAPPLE = new TreeGrower("crabapple", Optional.empty(), Optional.of(ModConfiguredFeatures.CRABAPPLE_KEY), Optional.empty());
    public static final TreeGrower OLIVE = new TreeGrower("olive", Optional.empty(), Optional.of(ModConfiguredFeatures.OLIVE_KEY), Optional.empty());
    public static final TreeGrower WHITE_CHERRY = new TreeGrower("white_cherry", Optional.empty(), Optional.of(ModConfiguredFeatures.WHITE_CHERRY_KEY), Optional.empty());
    public static final TreeGrower RED_CHERRY = new TreeGrower("red_cherry", Optional.empty(), Optional.of(ModConfiguredFeatures.RED_CHERRY_KEY), Optional.empty());
    public static final TreeGrower FIR = new TreeGrower("fir", Optional.empty(), Optional.of(ModConfiguredFeatures.FIR_KEY), Optional.empty());
    public static final TreeGrower WILLOW = new TreeGrower("willow", Optional.empty(), Optional.of(ModConfiguredFeatures.WILLOW_KEY), Optional.empty());
    public static final TreeGrower WORMTREE = new TreeGrower("wormtree", Optional.empty(), Optional.of(ModConfiguredFeatures.WORMTREE_KEY), Optional.empty());
    public static final TreeGrower ALMOND = new TreeGrower("almond", Optional.empty(), Optional.of(ModConfiguredFeatures.ALMOND_KEY), Optional.empty());
    public static final TreeGrower APPLE = new TreeGrower("apple", Optional.empty(), Optional.of(ModConfiguredFeatures.APPLE_KEY), Optional.empty());
    public static final TreeGrower APRICOT = new TreeGrower("apricot", Optional.empty(), Optional.of(ModConfiguredFeatures.APRICOT_KEY), Optional.empty());
    public static final TreeGrower BAOBAB = new TreeGrower("baobab", Optional.empty(), Optional.of(ModConfiguredFeatures.BAOBAB_KEY), Optional.empty());
    public static final TreeGrower BLACK_COTTONWOOD = new TreeGrower("black_cottonwood", Optional.empty(), Optional.of(ModConfiguredFeatures.BLACK_COTTONWOOD_KEY), Optional.empty());
    public static final TreeGrower BLACKTHORN = new TreeGrower("blackthorn", Optional.empty(), Optional.of(ModConfiguredFeatures.BLACKTHORN_KEY), Optional.empty());
    public static final TreeGrower BLOOD_ORANGE = new TreeGrower("blood_orange", Optional.empty(), Optional.of(ModConfiguredFeatures.BLOOD_ORANGE_KEY), Optional.empty());
    public static final TreeGrower BLOODWOOD = new TreeGrower("bloodwood", Optional.empty(), Optional.of(ModConfiguredFeatures.BLOODWOOD_KEY), Optional.empty());
    public static final TreeGrower BLUE_MAHOE = new TreeGrower("blue_mahoe", Optional.empty(), Optional.of(ModConfiguredFeatures.BLUE_MAHOE_KEY), Optional.empty());
    public static final TreeGrower COTTONWOOD = new TreeGrower("cottonwood", Optional.empty(), Optional.of(ModConfiguredFeatures.COTTONWOOD_KEY), Optional.empty());
    public static final TreeGrower DATEPALM = new TreeGrower("datepalm", Optional.empty(), Optional.of(ModConfiguredFeatures.DATEPALM_KEY), Optional.empty());
    public static final TreeGrower EBONY = new TreeGrower("ebony", Optional.empty(), Optional.of(ModConfiguredFeatures.EBONY_KEY), Optional.empty());
    public static final TreeGrower FIG = new TreeGrower("fig", Optional.empty(), Optional.of(ModConfiguredFeatures.FIG_KEY), Optional.empty());
    public static final TreeGrower FIREPLUM = new TreeGrower("fireplum", Optional.empty(), Optional.of(ModConfiguredFeatures.FIREPLUM_KEY), Optional.empty());
    public static final TreeGrower GOLDENHEART = new TreeGrower("goldenheart", Optional.empty(), Optional.of(ModConfiguredFeatures.GOLDENHEART_KEY), Optional.empty());
    public static final TreeGrower LEMON = new TreeGrower("lemon", Optional.empty(), Optional.of(ModConfiguredFeatures.LEMON_KEY), Optional.empty());
    public static final TreeGrower LIME = new TreeGrower("lime", Optional.empty(), Optional.of(ModConfiguredFeatures.LIME_KEY), Optional.empty());
    public static final TreeGrower LINDEN = new TreeGrower("linden", Optional.empty(), Optional.of(ModConfiguredFeatures.LINDEN_KEY), Optional.empty());
    public static final TreeGrower MAHOGANY = new TreeGrower("mahogany", Optional.empty(), Optional.of(ModConfiguredFeatures.MAHOGANY_KEY), Optional.empty());
    public static final TreeGrower MAPLE = new TreeGrower("maple", Optional.empty(), Optional.of(ModConfiguredFeatures.MAPLE_KEY), Optional.empty());
    public static final TreeGrower MYRRH = new TreeGrower("myrrh", Optional.empty(), Optional.of(ModConfiguredFeatures.MYRRH_KEY), Optional.empty());
    public static final TreeGrower NIGHTWOOD = new TreeGrower("nightwood", Optional.empty(), Optional.of(ModConfiguredFeatures.NIGHTWOOD_KEY), Optional.empty());
    public static final TreeGrower NUTMEG = new TreeGrower("nutmeg", Optional.empty(), Optional.of(ModConfiguredFeatures.NUTMEG_KEY), Optional.empty());
    public static final TreeGrower ORANGE = new TreeGrower("orange", Optional.empty(), Optional.of(ModConfiguredFeatures.ORANGE_KEY), Optional.empty());
    public static final TreeGrower PEACH = new TreeGrower("peach", Optional.empty(), Optional.of(ModConfiguredFeatures.PEACH_KEY), Optional.empty());
    public static final TreeGrower PEAR = new TreeGrower("pear", Optional.empty(), Optional.of(ModConfiguredFeatures.PEAR_KEY), Optional.empty());
    public static final TreeGrower PECAN = new TreeGrower("pecan", Optional.empty(), Optional.of(ModConfiguredFeatures.PECAN_KEY), Optional.empty());
    public static final TreeGrower PERSIMMON = new TreeGrower("persimmon", Optional.empty(), Optional.of(ModConfiguredFeatures.PERSIMMON_KEY), Optional.empty());
    public static final TreeGrower PINK_IVORY = new TreeGrower("pink_ivory", Optional.empty(), Optional.of(ModConfiguredFeatures.PINK_IVORY_KEY), Optional.empty());
    public static final TreeGrower PLUM = new TreeGrower("plum", Optional.empty(), Optional.of(ModConfiguredFeatures.PLUM_KEY), Optional.empty());
    public static final TreeGrower POMEGRANATE = new TreeGrower("pomegranate", Optional.empty(), Optional.of(ModConfiguredFeatures.POMEGRANATE_KEY), Optional.empty());
    public static final TreeGrower PURPLEHEART = new TreeGrower("purpleheart", Optional.empty(), Optional.of(ModConfiguredFeatures.PURPLEHEART_KEY), Optional.empty());
    public static final TreeGrower REDWOOD = new TreeGrower("redwood", Optional.empty(), Optional.of(ModConfiguredFeatures.REDWOOD_KEY), Optional.empty());
    public static final TreeGrower SANDALWOOD = new TreeGrower("sandalwood", Optional.empty(), Optional.of(ModConfiguredFeatures.SANDALWOOD_KEY), Optional.empty());
    public static final TreeGrower SANDBEGGAR = new TreeGrower("sandbeggar", Optional.empty(), Optional.of(ModConfiguredFeatures.SANDBEGGAR_KEY), Optional.empty());
    public static final TreeGrower TIGERWOOD = new TreeGrower("tigerwood", Optional.empty(), Optional.of(ModConfiguredFeatures.TIGERWOOD_KEY), Optional.empty());
    public static final TreeGrower YEW = new TreeGrower("yew", Optional.empty(), Optional.of(ModConfiguredFeatures.YEW_KEY), Optional.empty());
}
