package net.darkflameproduction.agotmod.util;

import net.darkflameproduction.agotmod.AGoTMod;
import net.minecraft.world.level.block.state.properties.BlockSetType;
import net.minecraft.world.level.block.state.properties.WoodType;

public class ModWoodTypes {
    public static final WoodType WEIRWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":weirwood", BlockSetType.OAK));
    public static final WoodType PINE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":pine", BlockSetType.OAK));
    public static final WoodType ASH = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":ash", BlockSetType.OAK));
    public static final WoodType BEECH = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":beech", BlockSetType.OAK));
    public static final WoodType CEDAR = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":cedar", BlockSetType.OAK));
    public static final WoodType CHESTNUT = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":chestnut", BlockSetType.OAK));
    public static final WoodType HAWTHORN = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":hawthorn", BlockSetType.OAK));
    public static final WoodType IRONWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":ironwood", BlockSetType.OAK));
    public static final WoodType SENTINEL = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":sentinel", BlockSetType.OAK));
    public static final WoodType SYCAMORE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":sycamore", BlockSetType.OAK));
    public static final WoodType BLACKBARK = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":blackbark", BlockSetType.OAK));
    public static final WoodType ASPEN = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":aspen", BlockSetType.OAK));
    public static final WoodType ALDER = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":alder", BlockSetType.OAK));
    public static final WoodType BLACK_CHERRY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":black_cherry", BlockSetType.OAK));
    public static final WoodType BLACK_OLIVE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":black_olive", BlockSetType.OAK));
    public static final WoodType CRABAPPLE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":crabapple", BlockSetType.OAK));
    public static final WoodType OLIVE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":olive", BlockSetType.OAK));
    public static final WoodType WHITE_CHERRY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":white_cherry", BlockSetType.OAK));
    public static final WoodType RED_CHERRY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":red_cherry", BlockSetType.OAK));
    public static final WoodType FIR = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":fir", BlockSetType.OAK));
    public static final WoodType WILLOW = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":willow", BlockSetType.OAK));
    public static final WoodType WORMTREE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":wormtree", BlockSetType.OAK));
    public static final WoodType ALMOND = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":almond", BlockSetType.OAK));
    public static final WoodType APPLE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":apple", BlockSetType.OAK));
    public static final WoodType APRICOT = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":apricot", BlockSetType.OAK));
    public static final WoodType BAOBAB = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":baobab", BlockSetType.OAK));
    public static final WoodType BLACK_COTTONWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":black_cottonwood", BlockSetType.OAK));
    public static final WoodType BLACKTHORN = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":blackthorn", BlockSetType.OAK));
    public static final WoodType BLOOD_ORANGE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":blood_orange", BlockSetType.OAK));
    public static final WoodType BLOODWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":bloodwood", BlockSetType.OAK));
    public static final WoodType BLUE_MAHOE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":blue_mahoe", BlockSetType.OAK));
    public static final WoodType COTTONWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":cottonwood", BlockSetType.OAK));
    public static final WoodType DATEPALM = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":datepalm", BlockSetType.OAK));
    public static final WoodType EBONY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":ebony", BlockSetType.OAK));
    public static final WoodType FIG = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":fig", BlockSetType.OAK));
    public static final WoodType FIREPLUM = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":fireplum", BlockSetType.OAK));
    public static final WoodType GOLDENHEART = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":goldenheart", BlockSetType.OAK));
    public static final WoodType LEMON = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":lemon", BlockSetType.OAK));
    public static final WoodType LIME = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":lime", BlockSetType.OAK));
    public static final WoodType LINDEN = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":linden", BlockSetType.OAK));
    public static final WoodType MAHOGANY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":mahogany", BlockSetType.OAK));
    public static final WoodType MAPLE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":maple", BlockSetType.OAK));
    public static final WoodType MYRRH = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":myrrh", BlockSetType.OAK));
    public static final WoodType NIGHTWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":nightwood", BlockSetType.OAK));
    public static final WoodType NUTMEG = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":nutmeg", BlockSetType.OAK));
    public static final WoodType ORANGE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":orange", BlockSetType.OAK));
    public static final WoodType PEACH = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":peach", BlockSetType.OAK));
    public static final WoodType PEAR = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":pear", BlockSetType.OAK));
    public static final WoodType PECAN = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":pecan", BlockSetType.OAK));
    public static final WoodType PERSIMMON = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":persimmon", BlockSetType.OAK));
    public static final WoodType PINK_IVORY = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":pink_ivory", BlockSetType.OAK));
    public static final WoodType PLUM = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":plum", BlockSetType.OAK));
    public static final WoodType POMEGRANATE = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":pomegranate", BlockSetType.OAK));
    public static final WoodType PURPLEHEART = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":purpleheart", BlockSetType.OAK));
    public static final WoodType REDWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":redwood", BlockSetType.OAK));
    public static final WoodType SANDALWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":sandalwood", BlockSetType.OAK));
    public static final WoodType SANDBEGGAR = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":sandbeggar", BlockSetType.OAK));
    public static final WoodType TIGERWOOD = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":tigerwood", BlockSetType.OAK));
    public static final WoodType YEW = WoodType.register(new WoodType(AGoTMod.MOD_ID + ":yew", BlockSetType.OAK));
}
